#include "stm32f446xx.h"

void config_clock(void){
	RCC->AHB1ENR |= (RCC_AHB1ENR_GPIOAEN) | (RCC_AHB1ENR_GPIOBEN) | (RCC_AHB1ENR_GPIOFEN) |(RCC_AHB1ENR_GPIOCEN) |
					(RCC_AHB1ENR_DMA2EN) | (RCC_AHB1ENR_DMA1EN);
	RCC->APB1ENR |= (RCC_APB1ENR_I2C1EN) | (RCC_APB1ENR_TIM3EN) | (RCC_APB1ENR_USART2EN) | (RCC_APB1ENR_I2C1EN) |
					(RCC_APB1ENR_TIM6EN) | (RCC_APB1ENR_TIM4EN) | (RCC_APB1ENR_TIM2EN);
	RCC->APB2ENR |= (RCC_APB2ENR_ADC1EN) | (RCC_APB2ENR_SYSCFGEN);
}
